name: Hi, I'm Hyunjong.
description: a Senior Analyst at IATA in Montréal
meta_description: "Hyunjong's personal blog"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: ""
domain_name: "http://hyunjongpark.com"
# google_analytics: "UA-XXXXXXXX-X"
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url: ""
author: "Hyunjong Park"

# Disqus config
disqus-shortname: ""
